"""Initial migration

Revision ID: 467dc3b557f4
Revises: bbbad9eebcb0
Create Date: 2026-07-04 17:20:27.395833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467dc3b557f4'
down_revision = 'bbbad9eebcb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_details',
    sa.Column('booking_detail_id', sa.Integer(), nullable=False),
    sa.Column('booking_userid', sa.Integer(), nullable=True),
    sa.Column('booking_propid', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('terms_agreed', sa.Boolean(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cleaning_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('booking_status', sa.Enum('pending_payment', 'paid', 'cancelled', name='booking_detail_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_propid'], ['properties.prop_id'], ),
    sa.ForeignKeyConstraint(['booking_userid'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_detail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_details')
    # ### end Alembic commands ###
