"""empty message

Revision ID: 7e77665bce2a
Revises: fc376b066194
Create Date: 2026-07-07 12:44:07.223137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e77665bce2a'
down_revision = 'fc376b066194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_number', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_in_number'), ['in_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_in_number'))
        batch_op.drop_column('in_number')

    # ### end Alembic commands ###
