"""empty message

Revision ID: a7bd5c224e22
Revises: fb3fc2defbe0
Create Date: 2026-06-26 05:01:01.160072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bd5c224e22'
down_revision = 'fb3fc2defbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('prop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prop_userid', sa.Integer(), nullable=False),
    sa.Column('pro_title', sa.String(length=255), nullable=False),
    sa.Column('prop_description', sa.Text(), nullable=True),
    sa.Column('prop_type', sa.Enum('Apartment', 'Duplex', 'Villas', 'Resorts', 'Studio', 'Bungalow', name='property_type'), nullable=True),
    sa.Column('pro_address', sa.String(length=255), nullable=True),
    sa.Column('pro_city', sa.String(length=255), nullable=True),
    sa.Column('price_per_night', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_guest', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('prop_availability_status', sa.Enum('available', 'booked', 'inactive', name='availability_status'), nullable=True),
    sa.Column('prop_mainimage_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['prop_userid'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prop_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
