"""empty message

Revision ID: afd0eea530fb
Revises: b793112f2816
Create Date: 2026-06-28 11:23:23.221197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd0eea530fb'
down_revision = 'b793112f2816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties_images',
    sa.Column('propimg_id', sa.Integer(), nullable=False),
    sa.Column('img_propid', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['img_propid'], ['properties.prop_id'], ),
    sa.PrimaryKeyConstraint('propimg_id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prop_category', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('prop_category')

    op.drop_table('properties_images')
    # ### end Alembic commands ###
