"""empty message

Revision ID: b793112f2816
Revises: d2606bdd8eae
Create Date: 2026-06-27 13:29:24.675645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b793112f2816'
down_revision = 'd2606bdd8eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('amenity_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('amenity_id')
    )
    op.create_table('property_states',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('property_types',
    sa.Column('prop_type_id', sa.Integer(), nullable=False),
    sa.Column('prop_typename', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('prop_type_id')
    )
    op.create_table('property_lgas',
    sa.Column('lga_id', sa.Integer(), nullable=False),
    sa.Column('lga_name', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['property_states.state_id'], ),
    sa.PrimaryKeyConstraint('lga_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('booking_userid', sa.Integer(), nullable=False),
    sa.Column('booking_propid', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('booking_status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='booking_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_propid'], ['properties.prop_id'], ),
    sa.ForeignKeyConstraint(['booking_userid'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('property_amenities',
    sa.Column('property_amenity_id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.amenity_id'], ),
    sa.ForeignKeyConstraint(['prop_id'], ['properties.prop_id'], ),
    sa.PrimaryKeyConstraint('property_amenity_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('review_propid', sa.Integer(), nullable=False),
    sa.Column('review_bookingid', sa.Integer(), nullable=False),
    sa.Column('review_userid', sa.Integer(), nullable=False),
    sa.Column('review_rating', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('review_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_bookingid'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['review_propid'], ['properties.prop_id'], ),
    sa.ForeignKeyConstraint(['review_userid'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prop_typeid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prop_stateid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prop_lgaid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prop_title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('prop_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prop_city', sa.String(length=150), nullable=True))
        batch_op.alter_column('prop_mainimage_url',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'property_lgas', ['prop_lgaid'], ['lga_id'])
        batch_op.create_foreign_key(None, 'property_types', ['prop_typeid'], ['prop_type_id'])
        batch_op.create_foreign_key(None, 'property_states', ['prop_stateid'], ['state_id'])
        batch_op.drop_column('prop_type')
        batch_op.drop_column('pro_title')
        batch_op.drop_column('pro_address')
        batch_op.drop_column('pro_city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pro_city', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('pro_address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('pro_title', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('prop_type', mysql.ENUM('Apartment', 'Duplex', 'Villas', 'Resorts', 'Studio', 'Bungalow'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('prop_mainimage_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('prop_city')
        batch_op.drop_column('prop_address')
        batch_op.drop_column('prop_title')
        batch_op.drop_column('prop_lgaid')
        batch_op.drop_column('prop_stateid')
        batch_op.drop_column('prop_typeid')

    op.drop_table('reviews')
    op.drop_table('property_amenities')
    op.drop_table('bookings')
    op.drop_table('property_lgas')
    op.drop_table('property_types')
    op.drop_table('property_states')
    op.drop_table('amenities')
    # ### end Alembic commands ###
