"""Initial migration

Revision ID: bbbad9eebcb0
Revises: afd0eea530fb
Create Date: 2026-07-04 02:00:10.367654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbbad9eebcb0'
down_revision = 'afd0eea530fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('admin_lastname')
        batch_op.drop_column('admin_firstname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_firstname', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('admin_lastname', mysql.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
