"""empty message

Revision ID: d2606bdd8eae
Revises: a7bd5c224e22
Create Date: 2026-06-26 07:41:14.481369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2606bdd8eae'
down_revision = 'a7bd5c224e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_firstname', sa.String(length=200), nullable=False),
    sa.Column('admin_lastname', sa.String(length=200), nullable=False),
    sa.Column('admin_email', sa.String(length=150), nullable=False),
    sa.Column('admin_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
