"""empty message

Revision ID: f1a4e1550248
Revises: c1f4d9a2e8b3
Create Date: 2026-07-10 03:05:26.597899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1a4e1550248'
down_revision = 'c1f4d9a2e8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('notification_title', sa.String(length=200), nullable=False),
    sa.Column('notification_message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('notification_icon', sa.String(length=50), nullable=True),
    sa.Column('notification_link', sa.String(length=255), nullable=True),
    sa.Column('notification_read_at', sa.DateTime(), nullable=True),
    sa.Column('notification_timecreated', sa.DateTime(), nullable=True),
    sa.Column('notification_timeupdated', sa.DateTime(), nullable=True),
    sa.Column('notification_reference_type', sa.String(length=50), nullable=True),
    sa.Column('notification_reference_id', sa.Integer(), nullable=True),
    sa.Column('notification_is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('item_name'))

    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('item_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('item_name'), ['item_name'], unique=True)

    op.drop_table('notifications')
    # ### end Alembic commands ###
