"""allow_nullable_and_guest_fields_on_reviews

Revision ID: f8a62e97f830
Revises: fec59ce4513c
Create Date: 2026-07-22 09:33:13.236633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8a62e97f830'
down_revision = 'fec59ce4513c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guest_email', sa.String(length=150), nullable=True))
        batch_op.alter_column('review_bookingid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('review_userid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review_userid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('review_bookingid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('guest_email')
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
