"""empty message

Revision ID: fb3fc2defbe0
Revises: 
Create Date: 2026-06-20 07:13:32.480672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb3fc2defbe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_firstname', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('user_lastname', sa.String(length=200), nullable=False))
        batch_op.alter_column('user_email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('user_phoneno',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('user_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user_role',
               existing_type=mysql.ENUM('customer', 'host', 'admin'),
               nullable=True)
        batch_op.alter_column('user_timecreated',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('user_timeupdated',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['user_email'])
        batch_op.create_unique_constraint(None, ['user_phoneno'])
        batch_op.drop_column('user_fullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_fullname', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_timeupdated',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('user_timecreated',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('user_role',
               existing_type=mysql.ENUM('customer', 'host', 'admin'),
               nullable=False)
        batch_op.alter_column('user_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('user_phoneno',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('user_lastname')
        batch_op.drop_column('user_firstname')

    # ### end Alembic commands ###
