"""empty message

Revision ID: fb3fc2defbe0
Revises: 
Create Date: 2026-06-20 07:13:32.480672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb3fc2defbe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_firstname', sa.String(length=200), nullable=False),
        sa.Column('user_lastname', sa.String(length=200), nullable=False),
        sa.Column('user_email', sa.String(length=150), nullable=False),
        sa.Column('user_phoneno', sa.String(length=50), nullable=False),
        sa.Column('user_password', sa.String(length=255), nullable=False),
        sa.Column('user_profileimage', sa.String(length=255), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True, default=False),
        sa.Column('user_status', sa.Enum('active', 'inactive', 'suspended', name='user_status'), nullable=True, default='active'),
        sa.Column('user_role', sa.Enum('customer', 'host', 'admin', name='user_role'), nullable=True, default='customer'),
        sa.Column('user_timecreated', sa.DateTime(), nullable=True),
        sa.Column('user_timeupdated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('user_email'),
        sa.UniqueConstraint('user_phoneno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
