"""empty message

Revision ID: fc376b066194
Revises: c31f2a9d8e10
Create Date: 2026-07-06 02:06:29.645196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc376b066194'
down_revision = 'c31f2a9d8e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
