"""empty message

Revision ID: fec59ce4513c
Revises: f1a4e1550248
Create Date: 2026-07-11 23:24:38.980471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fec59ce4513c'
down_revision = 'f1a4e1550248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('notification_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_link', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
